name: contact_add
description: "Add contacts to Android, iOS or macOS without additional permissions. This is done using native views for the user to complete the contact and save it to the address book."
version: 0.0.2
homepage: "https://github.com/yhlbr/contact_add"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ch.yannickh.contact_add
        pluginClass: ContactAddPlugin
      ios:
        pluginClass: ContactAddPlugin
      macos:
        pluginClass: ContactAddPlugin
